# docker compose file for batesste-minio

services:

  minio-server:
    build: 
      context: ./minio-server/
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: ${BATESSTE_MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${BATESSTE_MINIO_ROOT_PASSWORD}
    command: server --console-address ":9001" /data

  create-bucket:
    image: minio/mc:latest
    depends_on:
      - minio-server
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc config host add batesste-minio http://minio-server:9000 ${BATESSTE_MINIO_ACCESS_KEY} ${BATESSTE_MINIO_SECRET_KEY}) do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc mb batesste-minio/batesste-minio;
      exit 0;
      "

  minio-client:
    build: 
      context: ./minio-client/
      dockerfile: Dockerfile
    tty: true
    privileged: true
    devices:
      - /dev/fuse:/dev/fuse
    depends_on:
      - minio-server
      - create-bucket
    
volumes:
  minio_storage: {}

networks:
  default:
    name: batesste-minio
